"""
Export Simple Clothing Meshes to OBJ Format

Generates clothing meshes using SimpleClothingGenerator and exports them
as OBJ files for use in Blender.
"""

import numpy as np
import os
import sys

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from utils.simple_clothing import SimpleClothingGenerator


def write_obj(filepath, vertices, faces):
    """
    Write mesh to OBJ file.

    Args:
        filepath: Output OBJ file path
        vertices: Vertex positions [N, 3]
        faces: Face indices [F, 3]
    """
    with open(filepath, 'w') as f:
        # Write header
        f.write("# OBJ file generated by STAR Avatar\n")
        f.write(f"# Vertices: {len(vertices)}\n")
        f.write(f"# Faces: {len(faces)}\n\n")

        # Write vertices
        for v in vertices:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")

        f.write("\n")

        # Write faces (OBJ indices start at 1)
        for face in faces:
            f.write(f"f {face[0]+1} {face[1]+1} {face[2]+1}\n")

    print(f"✓ Saved: {filepath}")


def extract_clothing_region(vertices, faces, mask):
    """
    Extract clothing region as separate mesh.

    Args:
        vertices: All vertices [N, 3]
        faces: All faces [F, 3]
        mask: Boolean mask for clothing vertices [N]

    Returns:
        clothing_vertices, clothing_faces
    """
    # Find faces where at least 2 vertices are clothing
    faces_mask_count = np.sum(mask[faces], axis=1)
    clothing_faces_mask = faces_mask_count >= 2
    clothing_faces = faces[clothing_faces_mask]

    # Get unique vertices used in clothing faces
    clothing_vertex_indices = np.unique(clothing_faces.flatten())

    # Create new vertex array with only clothing vertices
    clothing_vertices = vertices[clothing_vertex_indices]

    # Remap face indices to new vertex array
    vertex_map = {old_idx: new_idx for new_idx, old_idx in enumerate(clothing_vertex_indices)}
    clothing_faces_remapped = np.array([
        [vertex_map[face[0]], vertex_map[face[1]], vertex_map[face[2]]]
        for face in clothing_faces
    ])

    return clothing_vertices, clothing_faces_remapped


def main():
    print("="*70)
    print("Export Clothing Meshes to OBJ")
    print("="*70)
    print()

    # Load STAR model
    star_model_path = "data/star_models/female/model.npz"
    print(f"Loading STAR model: {star_model_path}")

    if not os.path.exists(star_model_path):
        print(f"❌ STAR model not found: {star_model_path}")
        return

    star_data = np.load(star_model_path, allow_pickle=True)
    v_template = star_data['v_template']  # [6890, 3]
    faces = star_data['f']  # [13776, 3]

    print(f"✓ Loaded: {len(v_template)} vertices, {len(faces)} faces")
    print()

    # Initialize clothing generator
    generator = SimpleClothingGenerator()

    # Create output directory
    output_dir = "clothing"
    os.makedirs(output_dir, exist_ok=True)

    # Define clothing combinations to export
    clothing_configs = [
        {
            'name': 'sports_outfit',
            'types': ['sports_bra', 'shorts'],
            'description': 'Sports bra + shorts'
        },
        {
            'name': 'athletic_outfit',
            'types': ['tank_top', 'leggings'],
            'description': 'Tank top + leggings'
        },
        {
            'name': 'casual_outfit',
            'types': ['sports_bra', 'leggings'],
            'description': 'Sports bra + leggings'
        }
    ]

    # Generate and export each clothing configuration
    for config in clothing_configs:
        print(f"Generating: {config['description']}")

        # Apply clothing to base STAR template
        vertices_clothed, masks = generator.add_clothing(
            v_template.copy(),
            clothing_types=config['types'],
            return_masks=True
        )

        # Create combined mask for all clothing types in this config
        combined_mask = np.zeros(len(vertices_clothed), dtype=bool)
        for clothing_type in config['types']:
            if clothing_type in masks:
                combined_mask |= masks[clothing_type]

        # Extract clothing region
        clothing_vertices, clothing_faces = extract_clothing_region(
            vertices_clothed,
            faces,
            combined_mask
        )

        # Save as OBJ
        obj_path = os.path.join(output_dir, f"{config['name']}.obj")
        write_obj(obj_path, clothing_vertices, clothing_faces)

        print(f"  Clothing vertices: {len(clothing_vertices)}")
        print(f"  Clothing faces: {len(clothing_faces)}")
        print()

    # Also export individual garments
    print("Generating individual garments...")

    individual_garments = ['sports_bra', 'shorts', 'tank_top', 'leggings']

    for garment in individual_garments:
        vertices_clothed, masks = generator.add_clothing(
            v_template.copy(),
            clothing_types=[garment],
            return_masks=True
        )

        if garment in masks:
            clothing_vertices, clothing_faces = extract_clothing_region(
                vertices_clothed,
                faces,
                masks[garment]
            )

            obj_path = os.path.join(output_dir, f"{garment}.obj")
            write_obj(obj_path, clothing_vertices, clothing_faces)

            print(f"  {garment}: {len(clothing_vertices)} vertices, {len(clothing_faces)} faces")

    print()
    print("="*70)
    print("✓ All clothing meshes exported!")
    print("="*70)
    print(f"\nOutput directory: {os.path.abspath(output_dir)}")
    print()
    print("Next step:")
    print("  Run Blender with clothing:")
    print(f"    blender --background --python blender/star_clothing_renderer.py -- \\")
    print(f"        --star_model {star_model_path} \\")
    print(f"        --clothing_mesh clothing/sports_outfit.obj \\")
    print(f"        --hdri_dir data/hdri_backgrounds \\")
    print(f"        --output_dir outputs/blender_clothed \\")
    print(f"        --num_samples 5")
    print()


if __name__ == "__main__":
    main()
